Update Autopep8.yml

diff --git a/.github/workflows/Autopep8.yml b/.github/workflows/Autopep8.yml
--- a/.github/workflows/Autopep8.yml
+++ b/.github/workflows/Autopep8.yml
@@ -40,29 +40,21 @@ jobs:
         run: |
           git remote set-url origin https://x-access-token:${{ secrets.SE_HW2 }}@github.com/${{ github.repository }}.git
 
+      - name: Commit Autopep8 Changes
+        run: |
+          git add -A
+          git commit -m "Update python files with latest Autopep8 results" || echo "No changes to commit"
+
       - name: Fetch Latest Changes
         run: git fetch origin
 
       - name: Rebase Latest Changes
         run: |
           git rebase origin/main || {
-            echo "failed.";
+            echo "failed";
             exit 1;
           }
 
-      - name: Check for Changes
-        id: check-changes
+      - name: Push Changes
         run: |
-          git add -A
-          if git diff --cached --quiet; then
-            echo "No changes to commit"
-            echo "::set-output name=changes::false"
-          else
-            echo "::set-output name=changes::true"
-          fi
-
-      - name: Commit and Push Changes
-        if: steps.check-changes.outputs.changes == 'true'
-        run: |
-          git commit -m "Update python files with latest Autopep8 results"
           git push origin HEAD:main
